version: 0.2

phases:
  install:
    commands:
      - echo install phase
      - npm install
  pre_build:
    commands:
      - echo pre build phase
  build:
    commands:
      - echo build phase
      - npm build

  post_build:
    commands:
      - echo post build phase

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: dist/quickstart-nodejs